# Generated by Django 5.2.5 on 2025-08-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumhariapp', '0002_brand_image_category_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandid',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catid',
            new_name='category',
        ),
    ]
