# Generated by Django 5.2.5 on 2025-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumhariapp', '0003_rename_brandid_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
