# Generated by Django 5.2.5 on 2025-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumhariapp', '0004_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
