# Generated by Django 5.2.5 on 2025-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumhariapp', '0005_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='website',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
